name: openapi_migrate
version: 1.0.0
description: Intended to allow people to migrate their code to the new null safe style as an intermediary step
homepage: https://www.featurehub.io
repository: https://github.com/dart-ogurets/openapi_migrate
environment:
  sdk: '>=2.9.0 <3.0.0'
dependencies:
  collection: '^1.14.3'
  analyzer: ^0.39.17
  glob: ^2.0.1
  args: ^1.5.1
  yaml: ^2.2.1
  codemod: ^0.3.0
dev_dependencies:
  test: ^1.3.0

executables:
  openapi_migrate: openapi_migrate
